-- Deprecato: le policy legacy non applicavano correttamente i ruoli e
-- includevano un indirizzo email segnaposto. Non eseguire questo file.
-- Applicare database/migrations/20260928_scheduler_safety.sql nell'ambiente
-- di destinazione solo dopo averne verificato schema, ruoli e secrets.
