-- 1. Setup Tabelle Base
CREATE TABLE IF NOT EXISTS employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    matricola TEXT UNIQUE NOT NULL,
    nome_cognome TEXT NOT NULL,
    ruolo TEXT CHECK (ruolo IN ('INF', 'OSS')),
    team_id INTEGER, -- Identifica la "Tripletta" (1-5)
    limitazione_notte BOOLEAN DEFAULT FALSE,
    attivo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shift_types (
    codice TEXT PRIMARY KEY,
    peso_orario NUMERIC(4, 2) NOT NULL,
    descrizione TEXT
);

-- Popolamento Turni Standard
INSERT INTO shift_types (codice, peso_orario, descrizione) VALUES
('1', 7.0, 'Mattina'), ('K', 7.0, 'Pomeriggio'), ('N', 10.0, 'Notte'),
('S', 0.0, 'Smonto'), ('R', 0.0, 'Riposo'),
('F', 6.0, 'Ferie'), ('M', 6.0, 'Malattia'), ('104', 6.0, 'Legge 104'), ('P', 6.0, 'Permesso')
ON CONFLICT DO NOTHING;

-- 2. Tabella Operativa (Turni)
CREATE TABLE IF NOT EXISTS roster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(id),
    data DATE NOT NULL,
    shift_code TEXT REFERENCES shift_types(codice),
    is_locked BOOLEAN DEFAULT FALSE, -- Se TRUE, il solver non tocca questo turno
    UNIQUE(employee_id, data)
);

-- 3. Tabella Richieste
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(id),
    data_inizio DATE NOT NULL,
    data_fine DATE NOT NULL,
    tipo TEXT CHECK (tipo IN ('Ferie', 'Malattia', '104', 'Permesso')),
    stato TEXT DEFAULT 'Approvato',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
