-- Le policy precedenti usavano un indirizzo segnaposto e consentivano accessi
-- non coerenti con il login dell'applicazione. Non eseguire questo file.
-- Usare database/migrations/20260928_scheduler_safety.sql dopo aver verificato
-- lo schema, configurato i secrets server-side e impostato i ruoli Auth richiesti.
