-- Abilita RLS su tutte le tabelle critiche
ALTER TABLE roster ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE requests ENABLE ROW LEVEL SECURITY; -- Added just in case

-- 1. POLICY DI LETTURA (Tutti gli autenticati vedono i turni)
CREATE POLICY "Enable read access for all authenticated users"
ON roster FOR SELECT
TO authenticated
USING (true);

-- 2. POLICY DI SCRITTURA (Solo Admin)
-- Assumiamo che esista una tabella 'profiles' o un claim che identifica l'admin
-- Per MVP semplificato: L'email dell'admin è hardcodata o verificata
-- Nota: Sostituire 'email.del.caposala@ospedale.it' con la mail reale dell'admin
CREATE POLICY "Enable write access for admin only"
ON roster FOR ALL
TO authenticated
USING (auth.jwt() ->> 'email' = 'email.del.caposala@ospedale.it') 
WITH CHECK (auth.jwt() ->> 'email' = 'email.del.caposala@ospedale.it');

-- Tabella Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id), -- Chi ha fatto l'azione
    action_type TEXT NOT NULL, -- Es: 'UPDATE_SHIFT', 'GENERATE_ROSTER'
    target_resource TEXT, -- Es: 'Roster: Mario Rossi 25/10'
    old_value TEXT, -- Es: 'M'
    new_value TEXT, -- Es: 'N'
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Solo l'Admin può leggere i log. Nessuno può modificarli/cancellarli.
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admin read logs" ON audit_logs FOR SELECT TO authenticated USING (auth.jwt() ->> 'email' = 'email.del.caposala@ospedale.it');
CREATE POLICY "System insert logs" ON audit_logs FOR INSERT TO authenticated WITH CHECK (true);
