-- Migrazione locale pronta per revisione; non applicare a produzione senza
-- verificare prima il ruolo admin impostato negli app_metadata degli utenti.

ALTER TABLE public.employees
    ADD COLUMN IF NOT EXISTS contract_percentage NUMERIC(5, 2) NOT NULL DEFAULT 100
    CHECK (contract_percentage > 0 AND contract_percentage <= 100);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'requests' AND column_name = 'tipo'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'requests' AND column_name = 'tipo_richiesta'
    ) THEN
        ALTER TABLE public.requests RENAME COLUMN tipo TO tipo_richiesta;
    END IF;
END $$;

ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS stato TEXT NOT NULL DEFAULT 'APPROVED';

DO $$
DECLARE constraint_name TEXT;
BEGIN
    FOR constraint_name IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'public.requests'::regclass
          AND contype = 'c'
          AND (conname LIKE '%tipo_check' OR conname LIKE '%tipo_richiesta_check')
    LOOP
        EXECUTE format('ALTER TABLE public.requests DROP CONSTRAINT %I', constraint_name);
    END LOOP;
END $$;

UPDATE public.requests
SET tipo_richiesta = CASE upper(trim(tipo_richiesta))
    WHEN 'FERIE' THEN 'FERIE'
    WHEN 'MALATTIA' THEN 'MALATTIA'
    WHEN '104' THEN '104'
    WHEN 'PERMESSO' THEN 'PERMESSO'
    WHEN 'MATTINA (PREF)' THEN 'MATTINA (PREF)'
    WHEN 'POMERIGGIO (PREF)' THEN 'POMERIGGIO (PREF)'
    WHEN 'NOTTE (PREF)' THEN 'NOTTE (PREF)'
    ELSE tipo_richiesta
END;

ALTER TABLE public.requests
    ADD CONSTRAINT requests_tipo_richiesta_supported_check
    CHECK (upper(trim(tipo_richiesta)) IN (
        'FERIE', 'MALATTIA', '104', 'PERMESSO',
        'MATTINA (PREF)', 'POMERIGGIO (PREF)', 'NOTTE (PREF)'
    )) NOT VALID;

ALTER TABLE public.requests
    ADD CONSTRAINT requests_dates_ordered_check CHECK (data_fine >= data_inizio) NOT VALID;

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    action_type TEXT NOT NULL,
    target_resource TEXT,
    old_value TEXT,
    new_value TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roster ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.scheduler_settings (
    name TEXT PRIMARY KEY CHECK (name = 'default'),
    config JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.scheduler_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Scheduler settings admins only" ON public.scheduler_settings;
CREATE POLICY "Scheduler settings admins only" ON public.scheduler_settings
    FOR ALL TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "Enable read access for all authenticated users" ON public.roster;
DROP POLICY IF EXISTS "Enable write access for admin only" ON public.roster;
DROP POLICY IF EXISTS "Roster admins only" ON public.roster;
CREATE POLICY "Roster admins only" ON public.roster
    FOR ALL TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "Enable read access for all authenticated users" ON public.employees;
DROP POLICY IF EXISTS "Enable write access for admin only" ON public.employees;
DROP POLICY IF EXISTS "Employee admins only" ON public.employees;
CREATE POLICY "Employee admins only" ON public.employees
    FOR ALL TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "Enable read access for all authenticated users" ON public.requests;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.requests;
DROP POLICY IF EXISTS "Request admins only" ON public.requests;
CREATE POLICY "Request admins only" ON public.requests
    FOR ALL TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS "Admin read logs" ON public.audit_logs;
DROP POLICY IF EXISTS "System insert logs" ON public.audit_logs;
CREATE POLICY "Audit admins read" ON public.audit_logs
    FOR SELECT TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
CREATE POLICY "Audit admins write" ON public.audit_logs
    FOR INSERT TO authenticated
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- La vista pubblica non rivela il codice specifico di ferie, malattia, 104 o permesso.
CREATE OR REPLACE VIEW public.roster_calendar WITH (security_barrier = true) AS
SELECT r.employee_id,
       e.nome_cognome AS employee_name,
       e.matricola,
       e.ruolo,
       r.data,
       CASE WHEN r.shift_code IN ('F', 'M', '104', 'P') THEN 'ASS'
            ELSE r.shift_code END AS shift_code
FROM public.roster AS r
JOIN public.employees AS e ON e.id = r.employee_id;

REVOKE ALL ON public.roster, public.employees, public.requests, public.audit_logs FROM anon, authenticated;
REVOKE ALL ON public.scheduler_settings FROM anon, authenticated;
GRANT SELECT ON public.roster_calendar TO anon, authenticated;
GRANT ALL ON public.roster, public.employees, public.requests, public.audit_logs TO authenticated;
GRANT ALL ON public.scheduler_settings TO authenticated, service_role;
GRANT ALL ON public.roster, public.employees, public.requests, public.audit_logs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.audit_logs_id_seq TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.publish_roster_month(
    p_start DATE,
    p_end DATE,
    p_employee_ids UUID[],
    p_expected_roster JSONB,
    p_entries JSONB
) RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE
    current_snapshot JSONB;
    input_count INTEGER;
    unique_input_count INTEGER;
    saved_count INTEGER;
BEGIN
    IF coalesce(auth.role(), '') <> 'service_role'
       AND coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' THEN
        RAISE EXCEPTION 'Admin access required' USING ERRCODE = '42501';
    END IF;
    IF p_start IS NULL OR p_end < p_start OR p_employee_ids IS NULL
       OR cardinality(p_employee_ids) = 0 OR jsonb_typeof(p_entries) <> 'array' THEN
        RAISE EXCEPTION 'Invalid roster period or payload' USING ERRCODE = '22023';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtextextended('roster:' || p_start::TEXT || ':' || p_end::TEXT, 0));

    SELECT coalesce(jsonb_agg(jsonb_build_object(
        'employee_id', r.employee_id::TEXT,
        'data', r.data::TEXT,
        'shift_code', r.shift_code,
        'is_locked', r.is_locked
    ) ORDER BY r.employee_id, r.data), '[]'::JSONB)
    INTO current_snapshot
    FROM public.roster AS r
    WHERE r.data BETWEEN p_start AND p_end
      AND r.employee_id = ANY(p_employee_ids);

    IF current_snapshot IS DISTINCT FROM coalesce(p_expected_roster, '[]'::JSONB) THEN
        RAISE EXCEPTION 'Roster changed since draft creation; reload before publishing'
            USING ERRCODE = '40001';
    END IF;

    SELECT count(*)::INTEGER,
           count(DISTINCT ((value ->> 'employee_id') || ':' || (value ->> 'data')))::INTEGER
    INTO input_count, unique_input_count
    FROM jsonb_array_elements(p_entries);

    IF input_count <> unique_input_count
       OR input_count <> cardinality(p_employee_ids) * (p_end - p_start + 1)
       OR EXISTS (
           SELECT 1 FROM jsonb_array_elements(p_entries) AS x(value)
           WHERE (value ->> 'data')::DATE NOT BETWEEN p_start AND p_end
              OR NOT ((value ->> 'employee_id')::UUID = ANY(p_employee_ids))
              OR nullif(value ->> 'shift_code', '') IS NULL
       ) THEN
        RAISE EXCEPTION 'Roster draft must contain exactly one valid shift per employee and date'
            USING ERRCODE = '22023';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.roster AS locked
        WHERE locked.data BETWEEN p_start AND p_end
          AND locked.employee_id = ANY(p_employee_ids)
          AND locked.is_locked
          AND NOT EXISTS (
              SELECT 1 FROM jsonb_array_elements(p_entries) AS x(value)
              WHERE (value ->> 'employee_id')::UUID = locked.employee_id
                AND (value ->> 'data')::DATE = locked.data
                AND value ->> 'shift_code' = locked.shift_code
                AND coalesce((value ->> 'is_locked')::BOOLEAN, FALSE)
          )
    ) THEN
        RAISE EXCEPTION 'Locked roster assignments cannot be changed or unlocked'
            USING ERRCODE = '42501';
    END IF;

    DELETE FROM public.roster AS r
    WHERE r.data BETWEEN p_start AND p_end
      AND r.employee_id = ANY(p_employee_ids)
      AND NOT r.is_locked;

    INSERT INTO public.roster (employee_id, data, shift_code, is_locked)
    SELECT (value ->> 'employee_id')::UUID,
           (value ->> 'data')::DATE,
           value ->> 'shift_code',
           coalesce((value ->> 'is_locked')::BOOLEAN, FALSE)
    FROM jsonb_array_elements(p_entries) AS x(value)
    ON CONFLICT (employee_id, data) DO UPDATE
        SET shift_code = EXCLUDED.shift_code,
            is_locked = EXCLUDED.is_locked;

    GET DIAGNOSTICS saved_count = ROW_COUNT;

    INSERT INTO public.audit_logs (user_id, action_type, target_resource, old_value, new_value)
    VALUES (auth.uid(), 'PUBLISH_ROSTER', p_start::TEXT || ' — ' || p_end::TEXT,
            current_snapshot::TEXT, p_entries::TEXT);

    RETURN saved_count;
END;
$$;

REVOKE ALL ON FUNCTION public.publish_roster_month(DATE, DATE, UUID[], JSONB, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.publish_roster_month(DATE, DATE, UUID[], JSONB, JSONB) TO authenticated, service_role;
